### PR TITLE
Updated Metadata + Screenshots

### PR DESCRIPTION
**Pull request by mayankkuthar**

### CODE REVIEW

**Review by vipulgupta2048 — COMMENTED** [review]
Thanks for the patch @Gabbar8055
But we can't merge this until we have a fix for #3, #4 and #6. The activity needs a maintainer, first.
In reference to this, I am not sure of the source of the screenshots since the activity is not even running. 
The task clearly stated to run the activity on Sugar and then click screenshots to validate that the activity is actually working. 
If it is working on your system, then it would be helpful to know your system specifications.

**Comment by mayankkuthar** [comment]
The activity is running in my system.
I am running sugar in VMware workstation 11.0 with 588 MB Ram with Debian Linux as OS

**Comment by quozl** [comment]
@Gabbar8055, thanks, that's interesting that you have it working; please identify for me;
* what processor architecture; presumably Intel, but 32-bit or 64-bit emulation,
* what version of Debian,
* what version of GTK+,
* what version of Cairo.

Please also provide activity logs so it can be verified that the same errors are not happening for you.

**Comment by rhl-bthr** [comment]
Stale

**Pull request closed without merging**
